name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-version: 'latest'

      - name: Build application
        working-directory: "./20231633 Jared Jonosky SLD Formative"
        run: 'msbuild "20231633 Jared Jonosky SLD Formative.sln" /p:Configuration=Release'

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-version: 'latest'

      - name: Build application
        working-directory: "./20231633 Jared Jonosky SLD Formative"
        run: 'msbuild "20231633 Jared Jonosky SLD Formative.sln" /p:Configuration=Release'

  deploy:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-version: 'latest'

      - name: Build application
        working-directory: "./20231633 Jared Jonosky SLD Formative"
        run: 'msbuild "20231633 Jared Jonosky SLD Formative.sln" /p:Configuration=Release'
    
  notify:
    name: Notify team on success
    runs-on: windows-latest
    needs: [build, test, deploy]

    steps:
      - name: Check for build, test, or deployment success
        id: Check-status
        run: echo "Build, test, and deployment successful!"

      - name: Send notification on success
        if: steps.build.outcome == 'success' && steps.test.outcome == 'success' && steps.deploy.outcome == 'success'
        run: echo "Build, test, and deployment successful! Notify the team"